apiVersion: apps/v1
kind: Deployment

metadata:
  name: go-server
  labels:
    app: go-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: higorrsc/fc-hrsc-kubernetes-hello-go:v3
          env:
            - name: NAME
              value: "Higor"
            - name: AGE
              value: "41"
