apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: go-server-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: go-server
    kind: Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
