apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress-host
  annotations:
    spec.ingressClassName: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"

spec:
  rules:
    - host: go-server.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-server-service
                port:
                  number: 8080
  tls:
    - hosts:
        - go-server.local
      secretName: letsencrypt-tls
